#!/usr/bin/env zsh

mydir=`dirname $0`
if [[ $mydir = . ]]; then
	mydir=`pwd`
fi
dest=$HOME
echo My Directory: $mydir
mv $HOME/.zshenv $HOME/.zshenv.pre_zshkit
mv $HOME/.zshrc $HOME/.zshrc.pre_zshkit

cat > $HOME/.zshenv <<EOF
ZSHKIT=${mydir}
source \$ZSHKIT/zshenv
source ~/.zshenv.local

export ZSHKIT
EOF
cat > $HOME/.zshrc <<EOF
source \$ZSHKIT/zshrc
source ~/.zshrc.local
EOF
